execution:
  platform: android

server:
  url: http://127.0.0.1:4723

app:
  appPackage: com.wdiodemoapp
  appActivity: com.wdiodemoapp.SplashActivity
  appPath: app/webdriverio-app.apk

devices:

  - deviceName: Pixel_10
    platformVersion: "16"
    automationName: UiAutomator2
  - deviceName: Pixel_9_Pro
    platformVersion: "15"
    automationName: UiAutomator2